apiVersion: v1
kind: Pod
metadata:
  labels:
    run: frontend
  name: frontend
spec:
  containers:
  - image: franckcussac/awesome-webapp:latest
    name: frontend
    resources: {}
    envFrom:
      - configMapRef:
          name: frontend-config
  dnsPolicy: ClusterFirst
  restartPolicy: Always
